### ISSUE TITLE
v3.3 Tracker

### ISSUE THREAD

**Issue by NovaFox161** [Discord4J/Discord4J#1011]
This issue tracks all changes during the development of v3.3.0 and links to appropriate resources collecting migration notes with API and behavior changes.

## Documentation

- [ ] What's new in v3.3
- [ ] Migration notes

### Ports from 3.2.x
- [ ] Improved interactions in rest #1002
- [ ] Add getResolved methods for interactions #1007 
- [ ] Endpoint mode components & Content Menus #1008
- [ ] Permission override modification behavior #1009 

### 3.3.0
- [ ] Breaking channel hierarchy #960 
- [ ] Threads #958
- [ ] Improved stage channel support & stage instances #954 
- [ ] Support Guild Scheduled Events #1000 

### Needing Further Discussion
- [ ] OAuth2 Module #715 #908
