### ISSUE TITLE
Voice Module Improvements

### ISSUE THREAD

**Issue by darichey** [Discord4J/Discord4J#427]
This issue refers to [feature/voice](https://github.com/Discord4J/Discord4J/tree/feature/voice).

## Current State
The current state of the voice module.

The top level of the module is the `VoiceClient`. This is comparable to `RestClient` or `GatewayClient`. A `VoiceClient` is used to create and start a `VoiceGatewayClient` and `VoiceSocket`.

The module is exposed in `core` through `VoiceChannel#join()`. It asynchronously yields a `VoiceConnection` signalling that the connection with the voice gateway has completed. This is a similar pattern to the one used by reactor-netty in things such as `HttpClient` and `UdpClient`.

An `AudioProvider` has a single buffer which an implementer can write to in `provide()` which is called every 20 ms.

An `AudioReceiver` has a single buffer which an implementer can read from when `receive()` is called. A convenience overload is provided which extracts useful information from the buffer.

## Todo
At the moment, I consider the module to be complete enough to move forward. These are the remaining tasks:

- [x] Implement reconnect and resume functionality for VoiceGatewayClient
- [ ] Provide mappings for `ssrc -> user id` for receive
- [x] Handle multiple attempts to join the same channel
- [x] Handle moving channels
- [ ] Restructure to allow for custom voice clients like [DAN](https://github.com/Discord4J/DAN)
- [ ] Explore options for converting completely to netty's `ByteBuf`
- [ ] Add information to logger names to distinguish when multiple voice connections exist

Feel free to provide feedback in this issue.

Related tickets: #477 #495 #523

**Comment by danthonywalker** [comment]
You mentioned you have figured out a design that is to your liking. What is this design?

**Comment by danthonywalker** [comment]
At least from a `core` standpoint, I think it should mimic the behaviors of `DiscordClient` for consistency.
Two methods, one `connect` and one `disconnect` on `VoiceChannel`. `connect` returns a `Mono<Void>` that completes when disconnect and, of course, `disconnect` disconnects.

`connect` should take in a nullable `AudioReceiver` and `AudioProvider`. Both of which seem plenty self-explanatory and can mimic somewhat of the API in v2.

**Comment by GrandPanda** [comment]
I have updated this issue to reflect the implementation of voice found in #471.

**Comment by quanticc** [comment]
I provided an alternative implementation to the voice module that should help realizing most of the items laid out here. My idea is to cover them under a pattern that's admittedly easier to iterate upon and after that's done attempt to convert it to a FSM model.

**Comment by quanticc** [comment]
Unmarked items in the OP have lower priority. Depending on user interest they could be tracked as separate issues.
