### ISSUE TITLE
v3.1 Tracker

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#517]
Before a new development cycle begins we want to collect all ideas from the backlog and determine which ones are targeted for v3.1.0. 

## Pre-releases
- [x] M1 https://github.com/Discord4J/Discord4J/milestone/20?closed=1
- [x] M2 https://github.com/Discord4J/Discord4J/milestone/29?closed=1
- [x] RC1 https://github.com/Discord4J/Discord4J/milestone/33?closed=1
- [x] 3.1.0 https://github.com/Discord4J/Discord4J/milestone/18
    - [x] Add docs to new classes
    - [x] Getting started
    - [x] Music bot tutorial #685
    - [x] Error handling
    - [x] Sidebar
    - [x] [Threading](https://github.com/Discord4J/Discord4J/wiki/Threading-(v3.1))
    - [x] Migrating from v2.x to v3.1
    - [x] Logging
    - [x] [Migrating from v3.0 to v3.1](https://github.com/Discord4J/Discord4J/wiki/Migrating-from-v3.0-to-v3.1)
    - [x] [What's new in 3.1](https://github.com/Discord4J/Discord4J/wiki/What's-new-in-v3.1)

## Completed
- [x] Groundwork for rest-only entities #564 
- [x] Use reactor-core 3.3 and reactor-netty 0.9
- [x] Use reactor-pool in `GlobalRateLimiter` 44345e5
- [x] Organize default/managed reactor `Scheduler` instances
- [x] Consider decoupling a `DiscordClient` from a shard #483 #490 #564 
- [x] Improve `DiscordClientBuilder` API (remove getters, consider grouping methods by capability, allow opting out of `onOperatorDebug`)
- [x] Remove command module #565 
- [x] Distributed `ShardCoordinator` implementation #564 
- [x] Allow custom event loop group: `ReactorResources` for Rest, Gateway, Voice #564 #537 
- [x] Move time-capable `Scheduler` usage to `ReactorResources` where applicable (see comment below)
- [x] Update logging to include MDC-like contextual info (using Reactor Context)
- [x] Core API changes #534 #535 #540
- [x] Defer HTTP response body consumption #581
- [x] Addons module/project to place RSocket-based components #583
- [x] Update GatewayOptions and RouterOptions to be all-arg constructor instead of builder-based
- [x] Allow disabling guild subscriptions #586
- [x] Allow disabling guild member request ("member chunking") #587
- [x] Make decision about fetch strategy at `GatewayDiscordClient` level: **no REST fallback**
- [x] Refactor entities to use a combo of `Rest*` + `*Data` fields #522
- [x] Implement reconnect and resume functionality for VoiceGatewayClient #608
- [x] Restructure to allow for custom voice clients #608
- [x] Add information to logger names to distinguish when multiple voice connections exist #608
- [x] Finalize logger structure and levels

## Signature changes

- [x] Deprecate getters from `DiscordClientBuilder` during 3.0.x
- [x] Return `Optional` instead of `@Nullable` in `ClientException` #570
- [x] Consider refactoring `GatewayClient` constructor parameters into a builder
- [x] Return `Duration` from getResponseTime instead of long (millis) #574

## Behavior changes (#564)

- [x] **Make `DiscordClient#login()` complete on connect, not on disconnect**
- [x] `DiscordClient` as REST client wrapper. Can be used to work with REST API w/o caching or gateway.
- [x] `DiscordClient` is used to build a gateway shard group through `GatewayBootstrap`
- [x] All shards in a shard group send gateway updates to the same entity cache and also share the event dispatcher.
- [x] Remove `ShardingClientBuilder`
- [x] Remove `ServiceMediator`
- [x] Make `RetryOptions` a builder, keep the stateful bits private

## Repository chores

- [x] Switch master to 3.1 development and branch out `3.0.x`
- [x] Update .circleci/config.yml to also build `3.0.x` branch
- [x] Update README files

@Discord4J/members feel free to modify this ticket and also create tickets for these items as they get fleshed out.

## After release
- New API to build requests, enhancing `Spec` #585
- Event improvements #510
- Add more specific `ClientException` classes
- Add more specific `GatewayException` classes
- Lazy dispatch deserialization
- Improve how constants from `git.properties` file are loaded
- Consider webhook execution #547 
- Consider moving wiki to asciidoctor
- Consider an OAuth2 module

**Comment by quanticc** [comment]
I think we should change our default ``Scheduler`` usage through the library and open for customization from a class named `ReactorResources`. It can be set at core-level DiscordClient but overridden for Gateway and Voice separately. In general, we should move from elastic towards boundedElastic.

Here's a list of potential improvements to this area, by module:

## Core
#### BaseMessageChannel#typeUntil uses elastic (hardcoded)
- [ ] Action: Expose a "timerTaskScheduler" through ReactorResources (defaults to boundedElastic)

## Gateway
#### Heartbeat interval task uses elastic (hardcoded)
- [ ] Action: Expose a "timerTaskScheduler" through ReactorResources (defaults to boundedElastic)
#### Heartbeat ACKs are sent under elastic scheduler (hardcoded)
- [ ] Action: Expose a "timerTaskScheduler" through ReactorResources (defaults to boundedElastic)
#### Gateway outbound limiter uses single scheduler (hardcoded)
- [ ] Action: Move away from this limiter towards a pool-based one
#### Reconnect attempts use elastic scheduler (default)
- [ ] Action: Change default to boundedElastic. Keep location @ ReconnectOptions

## Rest
#### Responses are published under elastic scheduler (default)
- [ ] Action: Change default to boundedElastic. Keep location @ RouterOptions
#### Rate limited retries use "discord4j-worker" custom parallel scheduler (default)
- [ ] Action: Change default to boundedElastic. Keep location @ RouterOptions
#### If using SemaphoreGlobalRateLimiter, acquires permits under elastic scheduler (hardcoded)
- [ ] Action: Deprecate in v3.1 in favor of pool-based alternative

## Voice
#### Voice send task uses elastic scheduler (default)
- [ ] Action: Expose a "timerTaskScheduler" through ReactorResources (defaults to boundedElastic)
#### Voice heartbeat interval uses elastic scheduler (hardcoded)
- [ ] Action: Expose a "timerTaskScheduler" through ReactorResources (defaults to boundedElastic)

**Comment by quanticc** [comment]
Updating this to reflect our current state. After #584 has an initial push and we merge #608, I believe it's enough for a M1 pre-release.

@darichey what do you think?

**Comment by quanticc** [comment]
Updated the list of items we need to release 3.1.0.

There are a couple of critical issues in current master I'll fix before making a pre-release.

**Comment by quanticc** [comment]
Closing this as 3.1 is ready for release
