### ISSUE TITLE
Migrate from Response/Bean classes to immutable ones

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#584]

**Comment by darichey** [comment]
Drop `XBean` and `XResponse` layers in favor of a single `XData` layer. Deserialization will yield these directly both in `gateway` and `rest`. They will also be stored like `XBean` are today.

`XData` classes are immutable carriers of data, with no bells or whistles (they are perfect candidates for records). In retrospect...
1. There isn't much to gain from the disparity between `Response` and `Bean`
2. The bean spec isn't very beneficial to us

# Tasks
- [ ] Create `XData` classes corresponding to existing `XResponse` and `XBean` classes
- [ ] Lift restrictions in stores module to allow storing `XData`
- [ ] Migrate entity classes
- [ ] Migrate dispatch handlers

**Comment by quanticc** [comment]
We'll polish change/data branch and continue discussion in the original ticket #522
