### ISSUE TITLE
Support new fields in gateway payloads

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#596]
Discord deployed some gateway update that includes extra fields in some payloads. I'm not sure the type for these values, but in the meantime they cause errors and we discard them which is probably not what we want. 

If we know how those fields should work/type/structure, support it under this ticket. Otherwise let's fallback with the solution outlined in #595 until we know more about them.

**Comment by Shadorc** [comment]
There should be a new recently documented Activity#created_at field 
https://github.com/discordapp/discord-api-docs/commit/4fee0c3b0194832f32fb2f8d401dca6e2d6fdfe3

**Comment by quanticc** [comment]
Thanks!

I should mention that I'm looking for help to expose these fields as they get documented

**Comment by Shadorc** [comment]
There is also new Audit Log entries: 
https://github.com/discordapp/discord-api-docs/commit/65c06f75d59d1d371990a78f4a031af2a7c1f301

**Comment by Shadorc** [comment]
The `discord4j.gateway.json.dispatch.MessageUpdate["member"]` field is a partial member object without the `user` field and it would need a custom constructor for Member class.

Concerning `discord4j.gateway.json.dispatch.Ready["user_settings"]`, `discord4j.common.json.MessageMember["hoisted_role"]` and `discord4j.common.json.GuildMemberResponse["hoisted_role"]` they will probably never be documented because they don't seem to be usable for bots.

All other fields are undocumented or just not implemented in Discord4J yet.

**Comment by Shadorc** [comment]
Presence update fields are now fully documented: https://github.com/discordapp/discord-api-docs/commit/b20d1e78645b17699e202bf1fdf21e659bed555c

**Comment by Shadorc** [comment]
- [ ] discord4j.gateway.json.dispatch.Ready["user_settings"] (object) (!)
Intentionally undocumented: https://github.com/discordapp/discord-api-docs/issues/1239
 
- [ ] discord4j.common.json.UserResponse["verified"] (boolean), affects Ready (!)
This field is only received in the Ready payload, it could be optional because it cannot be presumed as false by default or ignored
 
- [X] discord4j.gateway.json.dispatch.MessageReactionAdd["member"]
Implemented
 
- [ ] discord4j.gateway.json.dispatch.GuildMemberUpdate["premium_since"]
Waiting for documentation
 
- [ ] discord4j.gateway.json.dispatch.TypingStart["member"]
Pull request is open: https://github.com/Discord4J/Discord4J/pull/598
 
- [ ] discord4j.common.json.MessageMember["hoisted_role"] in MessageCreate
Intentionally undocumented
 
- [ ] discord4j.gateway.json.dispatch.MessageUpdate["member"]
This field is a partial member object without the `user` field and it would need a custom constructor for Member class
 
- [ ] discord4j.common.json.GuildMemberResponse["hoisted_role"] within GuildMembersChunk["members"]
Intentionally undocumented
 
- [ ] discord4j.gateway.json.dispatch.PresenceUpdate["nick"]
Pull request is open: https://github.com/Discord4J/Discord4J/pull/600
 
- [ ] discord4j.gateway.json.dispatch.PresenceUpdate["premium_since"]
Pull request is open: https://github.com/Discord4J/Discord4J/pull/600
 
- [ ] (3.1) discord4j.gateway.json.response.ActivityResponse["id"] in PresenceUpdate["game"] and also affects GuildCreate (!)
Intentionally undocumented: https://github.com/discordapp/discord-api-docs/issues/1239
 
- [ ] (3.1) discord4j.gateway.json.response.ActivityResponse["created_at"]
Pull request is open: https://github.com/Discord4J/Discord4J/pull/601

**Comment by quanticc** [comment]
Undocumented fields will fall under #595 implementation. We're not expected to cover them -at this moment- so no further action on our part.

I updated your comment to reflect this and also what's already merged.

Audit log entries shall go on a separate ticket/PR.

@darichey What do you think about the following comment? In case @Shadorc or anyone wants to implement it.
> discord4j.gateway.json.dispatch.MessageUpdate["member"]
This field is a partial member object without the user field and it would need a custom constructor for Member class

**Comment by quanticc** [comment]
Closing this as 3.0 related tickets were merged. We can reopen if more appear or create a separate ticket now targeting 3.1.
