### ISSUE TITLE
v3.2 Tracker

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#748]
This issue tracks all changes during the development of v3.2.0 and links to appropriate resources collecting migration notes with API and behavior changes.

## Documentation

- [x] [What's new in v3.2](https://docs.discord4j.com/whats-new-in-v3-2)
- [x] [Migration notes](https://docs.discord4j.com/migrating-from-v3-1-to-v3-2)
- [x] Reference page for [Specs](https://docs.discord4j.com/specs)
- [x] Reference page for [Interactions](https://docs.discord4j.com/interactions)

### 3.2.0
- [x] Fix ephemeral messages filtering
- [x] Fix missing guildId in stored VoiceStates
- [x] MultipartRequest support to message edit route
- [x] Add context menu support #1001

### RC3
- [x] Fixes after RC2: [Milestone](https://github.com/Discord4J/Discord4J/milestone/51?closed=1)

### RC2
- [x] #959
- [x] Fixes since RC1: [Milestone](https://github.com/Discord4J/Discord4J/milestone/50?closed=1)

### RC1
- [x] New immutable specs #585 #927
- [x] New in-memory Store implementation #799

### M4
- [x] Improve working with audit logs #899
- [x] All Interactions changes from 3.1.6 + select-menus

### M3
- [x] Hotfixes after M2 release

### M2
- [x] Stores rework: abstraction to perform entity cache operations beyond CRUD #788
- [x] Provide API to bridge between old and new stores
- [x] Migrate to new ContextView Reactor API
- [x] Upgrade to Reactor Sinks/EmitResult API #796
- [x] Dedicated ID type for Data objects, storing them as long over String Discord4J/discord-json#20
- [x] Improve API for setting a client's status and activity #874 

### M1
- [x] Webhook execution #547 #742
- [x] Discord Gateway and REST API v8 Discord4J/discord-json#30 #785 #787
