### ISSUE TITLE
Application Commands

### ISSUE THREAD

**Issue by quanticc** [Discord4J/Discord4J#818]
New feature. Managing application commands through Discord4J (rest/core module) and handling interactions (first via gateway, then through rest)

## Work in progress with snapshot version published at #830

https://github.com/discord/discord-api-docs/pull/2295/files

API v6 supports this so this can be a 3.1 feature (3.1.x branch)
discord-json should go to 1.5.x branch

### Events
- [x] InteractionCreateEvent
- [x] ApplicationCommandCreateEvent
- [x] ApplicationCommandUpdateEvent
- [x] ApplicationCommandDeleteEvent

### Command registration
- [x] API to create application commands

### Interaction registry
- [x] Gateway event interactions
    - [x] Can obtain a `GatewayDiscordClient` through events
    - [x] Produces a `ReactiveEventAdapter` that implements `onReady` and `onInteractionCreateEvent`
    - [x] Allow creating/updating commands
- [x] Outgoing webhook interactions
    - [x] Requires access to a `RestClient`
    - [ ] Needs signature validation logic
    - [x] Produces a handler that can be applied to an `HttpServer`
    - [x] Allow creating/updating commands

### Global command routes
- [x] GET /applications/{application.id}/commands
- [x] POST /applications/{application.id}/commands
- [x] PATCH /applications/{application.id}/commands/{command.id}
- [x] DELETE /applications/{application.id}/commands/{command.id}

### Guild command routes
- [x] GET /applications/{application.id}/guilds/{guild.id}/commands
- [x] POST /applications/{application.id}/guilds/{guild.id}/commands
- [x] PATCH /applications/{application.id}/guilds/{guild.id}/commands/{command.id}
- [x] DELETE /applications/{application.id}/guilds/{guild.id}/commands/{command.id}

### Interaction routes - first response
- [x] POST /interactions/{interaction.id}/{interaction.token}/callback
- [x] PATCH /webhooks/{application.id}/{interaction.token}/messages/@original
- [x] DELETE /webhooks/{application.id}/{interaction.token}/messages/@original

### Interaction routes - followup messages
- [x] POST /webhooks/{application.id}/{interaction.token}/messages
- [x] PATCH /webhooks/{application.id}/{interaction.token}/messages/{message.id}

### Gateway event data objects
- [x] InteractionCreate
- [x] ApplicationCommandCreate
- [x] ApplicationCommandUpdate
- [x] ApplicationCommandDelete

Example payloads for the last 3: https://gist.github.com/quanticc/ffb0283c11e33ec38cdfcb72de39dc7d

### Command data objects
- [x] ApplicationCommand
- [x] ApplicationCommandEditRequest
- [x] ApplicationCommandOption
- [x] ApplicationCommandOptionType (enum at rest module)
- [x] ApplicationCommandOptionChoice

### Interaction data objects
- [x] Interaction
- [x] InteractionType (enum at rest module)
- [x] ApplicationCommandInteractionData
- [x] ApplicationCommandInteractionDataOption

### Interaction response data objects
- [x] InteractionResponse
- [x] InteractionResponseType (enum at rest module)
- [x] InteractionApplicationCommandCallbackData

**Comment by UnderMybrella** [comment]
I've added the data types to discord-json (https://github.com/Discord4J/discord-json/pull/43), beginning work now on integrating it into Discord4J o/

**Comment by quanticc** [comment]
Drafting some API at #830, snapshot included

**Comment by Shadorc** [comment]
Changes to interaction responses and flags: https://github.com/discord/discord-api-docs/pull/2615

**Comment by quanticc** [comment]
#850 was applied, including some breaking changes with it. A way to handle DM global commands separately from guild-source global commands was introduced:

```java
        Interactions interactions = Interactions.create()
                .onGlobalCommand(pingCommand,
                        createHandler()
                                .guild(interaction -> interaction.acknowledge()
                                        .withFollowup(it -> it.createFollowupMessage("Pong!")))
                                .direct(interaction -> interaction.reply("Direct Pong!"))
                                .build());
```

This is recommended because `RestInteraction` type won't give you access to guild or DM specific fields now.

Next up is covering the core-specific API and improving `InteractionCreateEvent`, which likely introduce more breaking changes.
